import {
  Laptop,
  Smartphone,
  Shirt,
  Watch,
  Home,
  Heart,
  Trophy,
  Gamepad,
  Car,
  Gift,
  Camera,
  Music,
  Book,
  Wrench,
  Tv,
  Speaker,
  Headphones,
  Coffee,
  Utensils,
  Baby,
  Dog,
  Cat,
  ShoppingBag,
  HardDrive,
  Cpu,
  Mouse,
  Keyboard,
  Monitor,
  Zap,
  Flame,
  Star,
  Globe,
  Plane,
  Compass,
  Briefcase,
  Wallet,
  CreditCard,
  Shield,
  Hammer,
  GraduationCap,
  Palette,
  Stethoscope,
  Sparkles,
  Video,
  Bike,
  Medal,
  Folder,
  Apple,
  Pizza,
  IceCream,
  Target,
} from 'lucide-react';

export const CATEGORY_ICONS = [
  { name: 'Folder', icon: Folder, color: 'text-amber-500' },
  { name: 'Laptop', icon: Laptop, color: 'text-blue-500' },
  { name: 'Smartphone', icon: Smartphone, color: 'text-slate-700' },
  { name: 'Tv', icon: Tv, color: 'text-zinc-800' },
  { name: 'Monitor', icon: Monitor, color: 'text-indigo-600' },
  { name: 'Cpu', icon: Cpu, color: 'text-primary' },
  { name: 'HardDrive', icon: HardDrive, color: 'text-slate-500' },
  { name: 'Mouse', icon: Mouse, color: 'text-orange-500' },
  { name: 'Keyboard', icon: Keyboard, color: 'text-violet-500' },
  { name: 'Headphones', icon: Headphones, color: 'text-pink-600' },
  { name: 'Speaker', icon: Speaker, color: 'text-rose-600' },
  { name: 'Zap', icon: Zap, color: 'text-yellow-500' },
  { name: 'Shirt', icon: Shirt, color: 'text-sky-500' },
  { name: 'Watch', icon: Watch, color: 'text-amber-700' },
  { name: 'ShoppingBag', icon: ShoppingBag, color: 'text-fuchsia-600' },
  { name: 'Tag', icon: Folder, color: 'text-red-500' }, // Note: Tag import was missing in previous list, using Folder as fallback or adding Tag
  { name: 'Home', icon: Home, color: 'text-orange-600' },
  { name: 'Utensils', icon: Utensils, color: 'text-slate-600' },
  { name: 'Coffee', icon: Coffee, color: 'text-amber-900' },
  { name: 'Apple', icon: Apple, color: 'text-red-600' },
  { name: 'Pizza', icon: Pizza, color: 'text-orange-500' },
  { name: 'IceCream', icon: IceCream, color: 'text-pink-400' },
  { name: 'Baby', icon: Baby, color: 'text-blue-400' },
  { name: 'ToyBrick', icon: Folder, color: 'text-red-500' }, // Fallback
  { name: 'Dog', icon: Dog, color: 'text-amber-600' },
  { name: 'Cat', icon: Cat, color: 'text-slate-500' },
  { name: 'Gamepad', icon: Gamepad, color: 'text-indigo-500' },
  { name: 'Trophy', icon: Trophy, color: 'text-yellow-600' },
  { name: 'Medal', icon: Medal, color: 'text-amber-500' },
  { name: 'Target', icon: Target, color: 'text-red-600' },
  { name: 'Star', icon: Star, color: 'text-yellow-400' },
  { name: 'Rocket', icon: Folder, color: 'text-slate-700' }, // Fallback
  { name: 'Flame', icon: Flame, color: 'text-orange-600' },
  { name: 'Globe', icon: Globe, color: 'text-blue-600' },
  { name: 'Plane', icon: Plane, color: 'text-sky-600' },
  { name: 'Compass', icon: Compass, color: 'text-primary' },
  { name: 'Briefcase', icon: Briefcase, color: 'text-stone-600' },
  { name: 'Wallet', icon: Wallet, color: 'text-primary' },
  { name: 'CreditCard', icon: CreditCard, color: 'text-blue-700' },
  { name: 'Shield', icon: Shield, color: 'text-indigo-700' },
  { name: 'Wrench', icon: Wrench, color: 'text-slate-600' },
  { name: 'Hammer', icon: Hammer, color: 'text-amber-800' },
  { name: 'Book', icon: Book, color: 'text-primary' },
  { name: 'GraduationCap', icon: GraduationCap, color: 'text-indigo-800' },
  { name: 'Palette', icon: Palette, color: 'text-pink-500' },
  { name: 'Heart', icon: Heart, color: 'text-rose-500' },
  { name: 'Stethoscope', icon: Stethoscope, color: 'text-cyan-600' },
  { name: 'Sparkles', icon: Sparkles, color: 'text-yellow-500' },
  { name: 'Camera', icon: Camera, color: 'text-zinc-700' },
  { name: 'Video', icon: Video, color: 'text-rose-500' },
  { name: 'Bike', icon: Bike, color: 'text-sky-500' },
  { name: 'Gift', icon: Gift, color: 'text-purple-600' },
];

export function getCategoryIcon(name: string) {
  return CATEGORY_ICONS.find((i) => i.name === name) || CATEGORY_ICONS[0]; // Fallback to Folder
}
