export enum ErrorUserCodes {
  // --- Business Logic Errors (FE needs these) ---
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  INVALID_USER_ID = 'INVALID_USER_ID',
  USER_DATA_MODIFIED_CONCURRENTLY = 'USER_DATA_MODIFIED_CONCURRENTLY',
  USER_ACCOUNT_LOCKED = 'USER_ACCOUNT_LOCKED',

  // --- Validation Errors (Format/Required) ---
  INVALID_STREET_FORMAT = 'STREET_IS_REQUIRED',
  INVALID_CITY_FORMAT = 'CITY_IS_REQUIRED',
  INVALID_NAME_FORMAT = 'NAME_MUST_BE_AT_LEAST_2_CHARS',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVALID_PASSWORD_FORMAT = 'PASSWORD_MUST_BE_AT_LEAST_6_CHARS',
  INVALID_PHONE_FORMAT = 'PHONE_NUMBER_MUST_BE_AT_LEAST_10_DIGITS',

  // --- Internal Server Errors ---
  USER_DATA_MAPPING_ERROR = 'USER_DATA_MAPPING_ERROR',
  CREATE_USER_FAILED = 'USER_CREATE_FAILED',
  USER_VERSION_IS_REQUIRED = 'USER_VERSION_IS_REQUIRED',
}

export enum ErrorAuthCodes {
  // --- Business Logic Errors ---
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_SESSION = 'INVALID_SESSION',
  TOKEN_REUSED_DETECTION = 'TOKEN_REUSED_DETECTION',
  EMAIL_VERIFICATION_LINK_ALREADY_USED = 'ACCOUNT_ALREADY_VERIFIED',
  EMAIL_RESET_PASSWORD_LINK_ALREADY_USED = 'LINK_ALREADY_USED',
  INVALID_OPAQUE_TOKEN = 'INVALID_URL',
  OPAQUE_TOKEN_EXPIRED = 'URL_EXPIRED',

  // --- Token/Session Errors ---
  UNAUTHORIZED_MISSING_TOKEN = 'UNAUTHORIZED_MISSING_TOKEN',
  UNAUTHORIZED_INVALID_TOKEN = 'UNAUTHORIZED_INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  
  // --- OAuth Errors ---
  GOOGLE_TOKEN_PAYLOAD_NOT_FOUND = 'GOOGLE_TOKEN_PAYLOAD_NOT_FOUND',
  INVALID_GOOGLE_TOKEN = 'INVALID_GOOGLE_TOKEN',
  INVALID_FACEBOOK_TOKEN = 'INVALID_FACEBOOK_TOKEN',

  // --- Internal Server Errors ---
  VERIFY_ACCOUNT_FAILED = 'VERIFY_ACCOUNT_FAILED',
  RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED',
}

export enum ErrorSystemCodes {
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum ErrorInfraCodes {
  // Database
  DATABASE_URI_REQUIRED = 'DATABASE_URI_REQUIRED',
  DATA_MODIFIED_CONCURRENTLY = 'DATA_MODIFIED_CONCURRENTLY',

  // Cache (Redis)
  REDIS_URI_REQUIRED = 'REDIS_URI_REQUIRED',
  REDIS_NOT_CONNECTED = 'REDIS_NOT_CONNECTED',

  // Email
  MISSING_EMAIL_API_KEY_IN_ENV = 'MISSING_EMAIL_API_KEY_IN_ENV',
  EMAIL_TEMPLATE_ERROR = 'EMAIL_TEMPLATE_ERROR',
  MISSING_REQUIRED_EMAIL_CONFIG_IN_ENV = 'MISSING_REQUIRED_EMAIL_CONFIG_IN_ENV',
  EMAIL_DELIVERY_FAILED = 'EMAIL_DELIVERY_FAILED',
}

export enum ErrorRBACCodes {
  ACCESS_DENIED_NO_ROLE = 'ACCESS_DENIED_NO_ROLE',
  ACCESS_DENIED_INSUFFICIENT_PERMISSIONS = 'ACCESS_DENIED_INSUFFICIENT_PERMISSIONS',
  CANNOT_CREATE_SUPER_ADMIN_VIA_API = 'CANNOT_CREATE_SUPER_ADMIN_VIA_API',
  ONLY_SUPER_ADMIN_CAN_CREATE_ADMINS = 'ONLY_SUPER_ADMIN_CAN_CREATE_ADMINS',
}
