export enum ErrorUserCodes {
  // --- Business Logic Errors (FE needs these) ---
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  INVALID_USER_ID = 'INVALID_USER_ID',
  USER_DATA_MODIFIED_CONCURRENTLY = 'USER_DATA_MODIFIED_CONCURRENTLY',
  USER_ACCOUNT_LOCKED = 'USER_ACCOUNT_LOCKED',

  // --- Validation Errors (Format/Required) ---
  INVALID_STREET_FORMAT = 'STREET_IS_REQUIRED',
  INVALID_CITY_FORMAT = 'CITY_IS_REQUIRED',
  INVALID_NAME_FORMAT = 'NAME_MUST_BE_AT_LEAST_2_CHARS',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVALID_PASSWORD_FORMAT = 'PASSWORD_MUST_BE_AT_LEAST_6_CHARS',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  PASSWORD_NEED_UPPERCASE = 'PASSWORD_NEED_UPPERCASE',
  PASSWORD_NEED_NUMBER = 'PASSWORD_NEED_NUMBER',
  PASSWORD_NEED_SPECIAL_CHAR = 'PASSWORD_NEED_SPECIAL_CHAR',
  INVALID_PHONE_FORMAT = 'PHONE_NUMBER_MUST_BE_AT_LEAST_10_DIGITS',
  PASSWORDS_DO_NOT_MATCH = 'PASSWORDS_DO_NOT_MATCH',

  // --- Internal Server Errors ---
  USER_DATA_MAPPING_ERROR = 'USER_DATA_MAPPING_ERROR',
  CREATE_USER_FAILED = 'USER_CREATE_FAILED',
  USER_VERSION_IS_REQUIRED = 'USER_VERSION_IS_REQUIRED',
  CONFIRM_PASSWORD_IS_REQUIRED = 'CONFIRM_PASSWORD_IS_REQUIRED',
}

export enum ErrorAuthCodes {
  // --- Business Logic Errors ---
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_SESSION = 'INVALID_SESSION',
  TOKEN_REUSED_DETECTION = 'TOKEN_REUSED_DETECTION',
  EMAIL_VERIFICATION_LINK_ALREADY_USED = 'ACCOUNT_ALREADY_VERIFIED',
  EMAIL_RESET_PASSWORD_LINK_ALREADY_USED = 'LINK_ALREADY_USED',
  INVALID_OPAQUE_TOKEN = 'INVALID_URL',
  OPAQUE_TOKEN_EXPIRED = 'URL_EXPIRED',

  // --- Token/Session Errors ---
  UNAUTHORIZED_MISSING_TOKEN = 'UNAUTHORIZED_MISSING_TOKEN',
  UNAUTHORIZED_INVALID_TOKEN = 'UNAUTHORIZED_INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',

  // --- OAuth Errors ---
  GOOGLE_TOKEN_PAYLOAD_NOT_FOUND = 'GOOGLE_TOKEN_PAYLOAD_NOT_FOUND',
  INVALID_GOOGLE_TOKEN = 'INVALID_GOOGLE_TOKEN',
  INVALID_FACEBOOK_TOKEN = 'INVALID_FACEBOOK_TOKEN',

  // --- Internal Server Errors ---
  VERIFY_ACCOUNT_FAILED = 'VERIFY_ACCOUNT_FAILED',
  RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED',
}

export enum ErrorSystemCodes {
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum ErrorCatalogCodes {
  NAME_IS_REQUIRED = 'NAME_MUST_BE_AT_LEAST_2_CHARS',
  SLUG_IS_REQUIRED = 'SLUG_MUST_BE_AT_LEAST_2_CHARS',
  DESCRIPTION_TOO_LONG = 'DESCRIPTION_TOO_LONG',
  BRAND_IS_REQUIRED = 'BRAND_IS_REQUIRED',
  CATEGORY_IS_REQUIRED = 'CATEGORY_IS_REQUIRED',
  SHORT_DESCRIPTION_IS_REQUIRED = 'SHORT_DESCRIPTION_IS_REQUIRED',
  AT_LEAST_ONE_SKU_REQUIRED = 'AT_LEAST_ONE_SKU_REQUIRED',
  SKU_CODE_REQUIRED = 'SKU_CODE_REQUIRED',
  PRICE_MUST_BE_POSITIVE = 'PRICE_MUST_BE_POSITIVE',
}

export enum ErrorInfraCodes {
  // Database
  DATABASE_URI_REQUIRED = 'DATABASE_URI_REQUIRED',
  DATA_MODIFIED_CONCURRENTLY = 'DATA_MODIFIED_CONCURRENTLY',

  // Cache (Redis)
  REDIS_URI_REQUIRED = 'REDIS_URI_REQUIRED',
  REDIS_NOT_CONNECTED = 'REDIS_NOT_CONNECTED',

  // Email
  MISSING_EMAIL_API_KEY_IN_ENV = 'MISSING_EMAIL_API_KEY_IN_ENV',
  EMAIL_TEMPLATE_ERROR = 'EMAIL_TEMPLATE_ERROR',
  MISSING_REQUIRED_EMAIL_CONFIG_IN_ENV = 'MISSING_REQUIRED_EMAIL_CONFIG_IN_ENV',
  EMAIL_DELIVERY_FAILED = 'EMAIL_DELIVERY_FAILED',
}

export enum ErrorRBACCodes {
  ACCESS_DENIED_NO_ROLE = 'ACCESS_DENIED_NO_ROLE',
  ACCESS_DENIED_INSUFFICIENT_PERMISSIONS = 'ACCESS_DENIED_INSUFFICIENT_PERMISSIONS',
  CANNOT_CREATE_OWNER_VIA_API = 'CANNOT_CREATE_OWNER_VIA_API',
  ONLY_OWNER_CAN_CREATE_ADMINS = 'ONLY_OWNER_CAN_CREATE_ADMINS',
  CANNOT_DELETE_SELF = 'CANNOT_DELETE_SELF',
  CANNOT_DELETE_OWNER = 'CANNOT_DELETE_OWNER',
  ONLY_OWNER_CAN_DELETE_ADMINS = 'ONLY_OWNER_CAN_DELETE_ADMINS',
  CANNOT_UPDATE_OWNER = 'CANNOT_UPDATE_OWNER',
  ONLY_OWNER_CAN_UPDATE_ADMINS = 'ONLY_OWNER_CAN_UPDATE_ADMINS',
}

export enum ClientErrorCodes {
  SOCIAL_LOGIN_FAILED = 'SOCIAL_LOGIN_FAILED',
  MISSING_CONFIG = 'MISSING_CONFIG',
  OAUTH_PROVIDER_IS_NOT_SUPPORTED = 'OAUTH_PROVIDER_IS_NOT_SUPPORTED',
  OAUTH_TOKEN_IS_REQUIRED = 'OAUTH_TOKEN_IS_REQUIRED',
  LOGIN_FAILED = 'LOGIN_FAILED',
  REGISTER_FAILED = 'REGISTER_FAILED',
}

export enum NiceToMeetYouCoder {
  DO_NOT_TOUCH_THIS_OR_YOU_WILL_BE_FIRED = 'Do not touch this or you will be fired',
  DO_NOT_TOUCH_THIS_OR_YOU_WILL_BE_FIRED_AGAIN = 'Do not touch this or you will be fired again',
  DO_NOT_TOUCH_THIS_OR_YOU_WILL_BE_FIRED_AGAIN_AND_AGAIN = 'Do not touch this or you will be fired again and again',
  DO_NOT_TOUCH_THIS_OR_YOUR_SYSTEM_WILL_CRASH = 'Do not touch this or your system will crash',
  DO_NOT_TOUCH_THIS_OR_YOUR_COMPUTER_WILL_EXPLODE = 'Do not touch this or your computer will explode',
  IF_YOU_STRESS_PLEASE_TAKE_A_BREAD_AND_A_COFFEE = 'If you stress please take a bread and a coffee',
  YOUR_GRAND_MOTHER_RUN_FASTER_THAN_YOUR_CODE = 'Your grand mother run faster than your code',
  I_WANT_TO_SAY_THANK_YOU_TO_MY_MOM = 'I want to say thank you to my mom',
  I_WANT_TO_SAY_THANK_YOU_TO_MY_MOM_AGAIN = 'I want to say thank you to my mom again',
  THIS_IS_A_JOKE_BRO = 'This is a joke bro',
  YOUR_MOM_FAT = 'Your mom fat',
  SORRY_I_AM_NOT_A_CODER = 'Sorry i am not a coder',
  THIS_ROW_IS_GENERATED_BY_AI = 'This row is generated by AI',
  ONE_DAY_YOU_WILL_BECOME_ELON_MUSK = 'One day you will become Elon Musk',
  DONALD_TRUMP_IS_MY_UNCLE = 'Donald Trump is my uncle',
  TWO_YEAR_I_DIDNT_TAKE_A_BATH = 'Two year i didnt take a bath',
  I_WANT_TO_SAY_THANK_YOU_TO_MY_CAT = 'I want to say thank you to my cat',
  NO_BODY_BELIEVES_IN_YOU = 'No body believes in you',
  YOUVE_LOST_AGAIN_AGAIN_AND_AGAIN = 'Youve lost again again and again',
  THE_LIGHTS_ARE_CUT_OFF = 'The lights are cut off',
  PLEASE_TURN_OFF_THE_LIGHT_BEFORE_LEAVING = 'Please turn off the light before leaving',
  I_WANT_TO_SAY_THANK_YOU_TO_MY_DOG = 'I want to say thank you to my dog',
  SEND_LOVE = 'If you try to attack my server, I will send nuclear to your country - Kim Jong Un',
  PUTIN_LOOK_AT_YOU = 'Putin look at you',
  I_WANT_TO_SAY_THANK_YOU_TO_PUTIN = 'I want to say thank you to Putin',
  EMOTIONAL_DAMAGE = 'Emotional damage',
  YOU_REALLY_DECODED_MY_SECRET = 'You really decoded my secret bro',
}
