@url_dev=http://localhost:3636/api
@email=kemmutat2k2@gmail.com
@password=coincard
@phone=0343564321

### 1. Register a new account (Public)
# @name register
POST {{url_dev}}/auth/register
Content-Type: application/json

{
    "name": "Hacker Lỏ",
    "email": "{{email}}",
    "password": "{{password}}",
    "phone": "{{phone}}"
}

### 2. Login
# @name login
POST {{url_dev}}/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### GET RESULT TOKENS
@accessToken = {{login.response.body.data.tokens.accessToken}}
@refreshToken = {{login.response.body.data.tokens.refreshToken}}

### 3. Refresh Token
POST {{url_dev}}/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "paste_rftk_here"
}

### GET RESULT TOKENS
@refreshToken = 

### 4. Logout (TODO: Implement later)
POST {{url_dev}}/auth/logout
Content-Type: application/json

{
    "refreshToken": "paste_reftk_here"
}

### Test auth route middleware
GET {{url_dev}}/health
Authorization: Bearer {{accessToken}}

### 5. Verify Email (Click from email)
# @name verifyEmail
@verifyToken = paste_token_from_db_here

GET {{url_dev}}/auth/verify-email?token={{verifyToken}}