/** @type {import('jest').Config} */
export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.spec.ts', '**/*.integration.spec.ts'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  moduleNameMapper: {
    '^(\\.\\./)+app$': '<rootDir>/src/app.ts',
    '^(\\.\\./)+container$': '<rootDir>/src/container.ts',
    '^\\./shared/(.*)\\.js$': '<rootDir>/src/shared/$1.ts',
    '^@modules/(.*)\\.js$': '<rootDir>/src/modules/$1.ts',
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@shared/(.*)\\.js$': '<rootDir>/src/shared/$1.ts',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@config/(.*)\\.js$': '<rootDir>/src/shared/configs/$1.ts',
    '^@config/(.*)$': '<rootDir>/src/shared/configs/$1',
    '^@core/(.*)\\.js$': '<rootDir>/src/shared/core/$1.ts',
    '^@core/(.*)$': '<rootDir>/src/shared/core/$1',
    '^@interfaces/(.*)\\.js$': '<rootDir>/src/shared/interfaces/$1.ts',
    '^@interfaces/(.*)$': '<rootDir>/src/shared/interfaces/$1',
    '^@enum/(.*)\\.js$': '<rootDir>/src/shared/enum/$1.ts',
    '^@enum/(.*)$': '<rootDir>/src/shared/enum/$1',
    '^@auth/(.*)\\.js$': '<rootDir>/src/modules/auth/$1.ts',
    '^@auth/(.*)$': '<rootDir>/src/modules/auth/$1',
    '^@monitoring/(.*)\\.js$': '<rootDir>/src/modules/monitoring/$1.ts',
    '^@monitoring/(.*)$': '<rootDir>/src/modules/monitoring/$1',
  },
  transform: {
    '^.+\\.tsx?$': ['ts-jest', { tsconfig: 'tsconfig.jest.json' }],
  },
  transformIgnorePatterns: ['/node_modules/(?!(.*\\.mjs$))'],
  testTimeout: 30000,
  verbose: true,
};
