@url_dev=http://localhost:5000/v1/api

### Find user
GET {{url_dev}}/users
Content-Type: application/json

### Create user
POST {{url_dev}}/users
Content-Type: application/json

{
    "name": "Hacker Lỏ",
    "email": "test55@gmail.com",
    "password": "abc123",
    "role": "user" 
}