export enum ErrorUserCodes {
  // --- Business Logic Errors (FE needs these) ---
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  INVALID_USER_ID = 'INVALID_USER_ID',
  USER_DATA_MODIFIED_CONCURRENTLY = 'USER_DATA_MODIFIED_CONCURRENTLY',

  // --- Validation Errors (Format/Required) ---
  INVALID_STREET_FORMAT = 'STREET_IS_REQUIRED',
  INVALID_CITY_FORMAT = 'CITY_IS_REQUIRED',
  INVALID_NAME_FORMAT = 'NAME_MUST_BE_AT_LEAST_2_CHARS',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVALID_PASSWORD_FORMAT = 'PASSWORD_MUST_BE_AT_LEAST_6_CHARS',
  INVALID_PHONE_FORMAT = 'PHONE_NUMBER_MUST_BE_AT_LEAST_10_DIGITS',

  // --- Internal Server Errors (FE usually just shows a generic message) ---
  USER_DATA_MAPPING_ERROR = 'USER_DATA_MAPPING_ERROR',
  CREATE_USER_FAILED = 'USER_CREATE_FAILED',
  USER_VERSION_IS_REQUIRED = 'USER_VERSION_IS_REQUIRED',
}

export enum ErrorAuthCodes {
  // --- Business Logic Errors (FE needs these) ---
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_SESSION = 'INVALID_SESSION', // Session expired or manually revoked
  TOKEN_REUSED_DETECTION = 'TOKEN_REUSED_DETECTION',
  EMAIL_VERIFICATION_LINK_ALREADY_USED = 'ACCOUNT_ALREADY_VERIFIED',
  EMAIL_RESET_PASSWORD_LINK_ALREADY_USED = 'LINK_ALREADY_USED',
  INVALID_OPAQUE_TOKEN = 'INVALID_URL',
  OPAQUE_TOKEN_EXPIRED = 'URL_EXPIRED',

  // --- Internal Server Errors (FE usually just shows a generic message) ---
  VERIFY_ACCOUNT_FAILED = 'VERIFY_ACCOUNT_FAILED',
  RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED',
}
