import mongoose from 'mongoose';
import { PRODUCT_STATUS } from '@atomecom/shared';

const categories = [
  // --- ELECTRONICS (25) ---
  {
    name: 'Electronics',
    slug: 'electronics',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Consumer electronics and gadgets',
    icon: 'laptop',
  },
  {
    name: 'Smartphones',
    slug: 'smartphones',
    parentSlug: 'electronics',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Mobile phones and accessories',
    icon: 'smartphone',
  },
  {
    name: 'iPhone',
    slug: 'iphone',
    parentSlug: 'smartphones',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Apple smartphones',
    icon: 'smartphone',
  },
  {
    name: 'Samsung',
    slug: 'samsung-phones',
    parentSlug: 'smartphones',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Samsung smartphones',
    icon: 'smartphone',
  },
  {
    name: 'Android Phones',
    slug: 'android-phones',
    parentSlug: 'smartphones',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Other Android smartphones',
    icon: 'smartphone',
  },
  {
    name: 'Phone Cases',
    slug: 'phone-cases',
    parentSlug: 'smartphones',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Protective cases',
    icon: 'package',
  },
  {
    name: 'Power Banks',
    slug: 'power-banks',
    parentSlug: 'smartphones',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Portable chargers',
    icon: 'battery',
  },
  {
    name: 'Laptops',
    slug: 'laptops',
    parentSlug: 'electronics',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Work and gaming laptops',
    icon: 'laptop',
  },
  {
    name: 'MacBook',
    slug: 'macbook',
    parentSlug: 'laptops',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Apple laptops',
    icon: 'laptop',
  },
  {
    name: 'Gaming Laptops',
    slug: 'gaming-laptops',
    parentSlug: 'laptops',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'High performance gaming rigs',
    icon: 'zap',
  },
  {
    name: 'Ultrabooks',
    slug: 'ultrabooks',
    parentSlug: 'laptops',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Thin and light laptops',
    icon: 'laptop',
  },
  {
    name: 'Laptop Bags',
    slug: 'laptop-bags',
    parentSlug: 'laptops',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Protective bags',
    icon: 'shopping-bag',
  },
  {
    name: 'Audio',
    slug: 'audio',
    parentSlug: 'electronics',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Headphones, speakers and earbuds',
    icon: 'headphones',
  },
  {
    name: 'Headphones',
    slug: 'headphones',
    parentSlug: 'audio',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Over-ear and on-ear headphones',
    icon: 'headphones',
  },
  {
    name: 'Earbuds',
    slug: 'earbuds',
    parentSlug: 'audio',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'True wireless earbuds',
    icon: 'bluetooth',
  },
  {
    name: 'Bluetooth Speakers',
    slug: 'bluetooth-speakers',
    parentSlug: 'audio',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Portable speakers',
    icon: 'speaker',
  },
  {
    name: 'Home Audio',
    slug: 'home-audio',
    parentSlug: 'audio',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Soundbars and systems',
    icon: 'music',
  },
  {
    name: 'Cameras',
    slug: 'cameras',
    parentSlug: 'electronics',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Digital cameras and lenses',
    icon: 'camera',
  },
  {
    name: 'DSLR',
    slug: 'dslr-cameras',
    parentSlug: 'cameras',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Professional DSLR cameras',
    icon: 'camera',
  },
  {
    name: 'Mirrorless',
    slug: 'mirrorless-cameras',
    parentSlug: 'cameras',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Modern mirrorless cameras',
    icon: 'camera',
  },
  {
    name: 'Action Cameras',
    slug: 'action-cameras',
    parentSlug: 'cameras',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'GoPro and more',
    icon: 'video',
  },
  {
    name: 'Lenses',
    slug: 'camera-lenses',
    parentSlug: 'cameras',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Camera lenses',
    icon: 'target',
  },
  {
    name: 'Computer Components',
    slug: 'pc-components',
    parentSlug: 'electronics',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'CPUs, GPUs, RAM',
    icon: 'cpu',
  },
  {
    name: 'Processors',
    slug: 'pc-processors',
    parentSlug: 'pc-components',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Intel and AMD',
    icon: 'cpu',
  },
  {
    name: 'Graphics Cards',
    slug: 'gpu',
    parentSlug: 'pc-components',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'NVIDIA and AMD',
    icon: 'zap',
  },

  // --- FASHION (25) ---
  {
    name: 'Fashion',
    slug: 'fashion',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Clothing, shoes and accessories',
    icon: 'shirt',
  },
  {
    name: 'Men Clothing',
    slug: 'men-clothing',
    parentSlug: 'fashion',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Fashion for men',
    icon: 'user',
  },
  {
    name: 'T-Shirts',
    slug: 'men-tshirts',
    parentSlug: 'men-clothing',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Casual t-shirts for men',
    icon: 'shirt',
  },
  {
    name: 'Jeans',
    slug: 'men-jeans',
    parentSlug: 'men-clothing',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Denim pants for men',
    icon: 'layers',
  },
  {
    name: 'Shirts',
    slug: 'men-shirts',
    parentSlug: 'men-clothing',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Formal and casual shirts',
    icon: 'shirt',
  },
  {
    name: 'Jackets',
    slug: 'men-jackets',
    parentSlug: 'men-clothing',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Outerwear for men',
    icon: 'wind',
  },
  {
    name: 'Suits',
    slug: 'men-suits',
    parentSlug: 'men-clothing',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Formal suits',
    icon: 'user',
  },
  {
    name: 'Women Clothing',
    slug: 'women-clothing',
    parentSlug: 'fashion',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Fashion for women',
    icon: 'user-plus',
  },
  {
    name: 'Dresses',
    slug: 'women-dresses',
    parentSlug: 'women-clothing',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Elegant dresses for women',
    icon: 'clover',
  },
  {
    name: 'Skirts',
    slug: 'women-skirts',
    parentSlug: 'women-clothing',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Stylish skirts',
    icon: 'clover',
  },
  {
    name: 'Tops',
    slug: 'women-tops',
    parentSlug: 'women-clothing',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Blouses and t-shirts',
    icon: 'shirt',
  },
  {
    name: 'Lingerie',
    slug: 'women-lingerie',
    parentSlug: 'women-clothing',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Women underwear',
    icon: 'heart',
  },
  {
    name: 'Activewear',
    slug: 'women-activewear',
    parentSlug: 'women-clothing',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Sports clothes for women',
    icon: 'activity',
  },
  {
    name: 'Shoes',
    slug: 'shoes',
    parentSlug: 'fashion',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Footwear for all',
    icon: 'footprints',
  },
  {
    name: 'Men Shoes',
    slug: 'men-shoes',
    parentSlug: 'shoes',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Shoes for men',
    icon: 'footprints',
  },
  {
    name: 'Sneakers',
    slug: 'men-sneakers',
    parentSlug: 'men-shoes',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Casual sneakers',
    icon: 'footprints',
  },
  {
    name: 'Boots',
    slug: 'men-boots',
    parentSlug: 'men-shoes',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Winter and work boots',
    icon: 'footprints',
  },
  {
    name: 'Women Shoes',
    slug: 'women-shoes',
    parentSlug: 'shoes',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Shoes for women',
    icon: 'footprints',
  },
  {
    name: 'Heels',
    slug: 'women-heels',
    parentSlug: 'women-shoes',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'High heels',
    icon: 'footprints',
  },
  {
    name: 'Flats',
    slug: 'women-flats',
    parentSlug: 'women-shoes',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Comfortable flat shoes',
    icon: 'footprints',
  },
  {
    name: 'Accessories',
    slug: 'fashion-accessories',
    parentSlug: 'fashion',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Watches, bags and jewelry',
    icon: 'watch',
  },
  {
    name: 'Watches',
    slug: 'watches',
    parentSlug: 'fashion-accessories',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Timepieces for men and women',
    icon: 'watch',
  },
  {
    name: 'Handbags',
    slug: 'handbags',
    parentSlug: 'fashion-accessories',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Women bags and purses',
    icon: 'shopping-bag',
  },
  {
    name: 'Jewelry',
    slug: 'jewelry',
    parentSlug: 'fashion-accessories',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Necklaces, earrings',
    icon: 'gem',
  },
  {
    name: 'Belts',
    slug: 'fashion-belts',
    parentSlug: 'fashion-accessories',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Leather belts',
    icon: 'wind',
  },

  // --- HOME & LIVING (25) ---
  {
    name: 'Home & Living',
    slug: 'home-living',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Furniture, decor and kitchenware',
    icon: 'home',
  },
  {
    name: 'Kitchen',
    slug: 'kitchen',
    parentSlug: 'home-living',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Cookware and kitchen appliances',
    icon: 'utensils',
  },
  {
    name: 'Cookware',
    slug: 'cookware',
    parentSlug: 'kitchen',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Pots, pans and more',
    icon: 'utensils',
  },
  {
    name: 'Bakeware',
    slug: 'bakeware',
    parentSlug: 'kitchen',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Baking tins and accessories',
    icon: 'cake',
  },
  {
    name: 'Coffee Makers',
    slug: 'coffee-makers',
    parentSlug: 'kitchen',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Daily coffee machines',
    icon: 'coffee',
  },
  {
    name: 'Small Appliances',
    slug: 'small-appliances',
    parentSlug: 'kitchen',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Blenders, toasters, etc.',
    icon: 'plug',
  },
  {
    name: 'Bedroom',
    slug: 'bedroom',
    parentSlug: 'home-living',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Beds, mattresses and bedding',
    icon: 'bed',
  },
  {
    name: 'Bedding',
    slug: 'bedding',
    parentSlug: 'bedroom',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Sheets, pillows and covers',
    icon: 'layers',
  },
  {
    name: 'Mattresses',
    slug: 'mattresses',
    parentSlug: 'bedroom',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'High quality mattresses',
    icon: 'bed',
  },
  {
    name: 'Furniture',
    slug: 'home-furniture',
    parentSlug: 'home-living',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Living room and office furniture',
    icon: 'table',
  },
  {
    name: 'Living Room',
    slug: 'living-room-furniture',
    parentSlug: 'home-furniture',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Sofas, coffee tables',
    icon: 'sofa',
  },
  {
    name: 'Dining Room',
    slug: 'dining-room-furniture',
    parentSlug: 'home-furniture',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Dining tables, chairs',
    icon: 'table',
  },
  {
    name: 'Office Furniture',
    slug: 'office-furniture',
    parentSlug: 'home-furniture',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Desks, office chairs',
    icon: 'briefcase',
  },
  {
    name: 'Home Decor',
    slug: 'home-decor',
    parentSlug: 'home-living',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Wall art, lamps, rugs',
    icon: 'lamp',
  },
  {
    name: 'Wall Art',
    slug: 'wall-art',
    parentSlug: 'home-decor',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Paintings and posters',
    icon: 'image',
  },
  {
    name: 'Lighting',
    slug: 'home-lighting',
    parentSlug: 'home-decor',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Lamps and ceiling lights',
    icon: 'sun',
  },
  {
    name: 'Rugs',
    slug: 'home-rugs',
    parentSlug: 'home-decor',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Area rugs and carpets',
    icon: 'layers',
  },
  {
    name: 'Bathroom',
    slug: 'bathroom',
    parentSlug: 'home-living',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Towels, bathroom accessories',
    icon: 'bath',
  },
  {
    name: 'Towels',
    slug: 'bathroom-towels',
    parentSlug: 'bathroom',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Cotton towels',
    icon: 'layers',
  },
  {
    name: 'Shower',
    slug: 'shower-accessories',
    parentSlug: 'bathroom',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Curtains and heads',
    icon: 'bath',
  },
  {
    name: 'Storage',
    slug: 'storage-organization',
    parentSlug: 'home-living',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Boxes, shelves, organizers',
    icon: 'archive',
  },
  {
    name: 'Boxes',
    slug: 'storage-boxes',
    parentSlug: 'storage-organization',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Plastic and wood boxes',
    icon: 'box',
  },
  {
    name: 'Shelves',
    slug: 'storage-shelves',
    parentSlug: 'storage-organization',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Wall and standing shelves',
    icon: 'align-justify',
  },
  {
    name: 'Garden',
    slug: 'garden-outdoors',
    parentSlug: 'home-living',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Plants and garden tools',
    icon: 'flower',
  },
  {
    name: 'Garden Tools',
    slug: 'garden-tools',
    parentSlug: 'garden-outdoors',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Shovels, rakes, etc.',
    icon: 'wrench',
  },

  // --- BEAUTY & HEALTH (15) ---
  {
    name: 'Beauty & Health',
    slug: 'beauty-health',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Skincare, makeup and personal care',
    icon: 'heart',
  },
  {
    name: 'Skincare',
    slug: 'skincare',
    parentSlug: 'beauty-health',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Face and body care products',
    icon: 'sparkles',
  },
  {
    name: 'Facial Care',
    slug: 'facial-care',
    parentSlug: 'skincare',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Cleansers, serums and moisturizers',
    icon: 'sparkles',
  },
  {
    name: 'Sun Care',
    slug: 'sun-care',
    parentSlug: 'skincare',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Sunscreen and after-sun',
    icon: 'sun',
  },
  {
    name: 'Makeup',
    slug: 'makeup',
    parentSlug: 'beauty-health',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Cosmetics for face, eyes and lips',
    icon: 'palette',
  },
  {
    name: 'Face Makeup',
    slug: 'face-makeup',
    parentSlug: 'makeup',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Foundations and powders',
    icon: 'smile',
  },
  {
    name: 'Eye Makeup',
    slug: 'eye-makeup',
    parentSlug: 'makeup',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Mascara and eyeshadow',
    icon: 'eye',
  },
  {
    name: 'Hair Care',
    slug: 'hair-care',
    parentSlug: 'beauty-health',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Shampoos and conditioners',
    icon: 'scissors',
  },
  {
    name: 'Hair Styling',
    slug: 'hair-styling',
    parentSlug: 'hair-care',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Gels, sprays and tools',
    icon: 'scissors',
  },
  {
    name: 'Personal Care',
    slug: 'personal-care',
    parentSlug: 'beauty-health',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Oral care, hair care and hygiene',
    icon: 'bath',
  },
  {
    name: 'Health',
    slug: 'health-wellness',
    parentSlug: 'beauty-health',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Supplements and vitamins',
    icon: 'plus-circle',
  },
  {
    name: 'Supplements',
    slug: 'health-supplements',
    parentSlug: 'health-wellness',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Protein, vitamins',
    icon: 'activity',
  },
  {
    name: 'Medical Supplies',
    slug: 'medical-supplies',
    parentSlug: 'health-wellness',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'First aid, monitors',
    icon: 'thermometer',
  },
  {
    name: 'Fragrances',
    slug: 'fragrances',
    parentSlug: 'beauty-health',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Perfumes and colognes',
    icon: 'droplet',
  },
  {
    name: 'Men Fragrances',
    slug: 'men-fragrances',
    parentSlug: 'fragrances',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Cologne for men',
    icon: 'droplet',
  },

  // --- SPORTS & OUTDOORS (15) ---
  {
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Fitness, outdoor and sports gear',
    icon: 'trophy',
  },
  {
    name: 'Fitness',
    slug: 'fitness-gear',
    parentSlug: 'sports-outdoors',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Gym and yoga equipment',
    icon: 'activity',
  },
  {
    name: 'Yoga',
    slug: 'yoga-accessories',
    parentSlug: 'fitness-gear',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Mats, blocks and straps',
    icon: 'activity',
  },
  {
    name: 'Gym Equipment',
    slug: 'gym-equipment',
    parentSlug: 'fitness-gear',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Dumbbells, treadmills',
    icon: 'dumbbell',
  },
  {
    name: 'Outdoor',
    slug: 'outdoor-adventure',
    parentSlug: 'sports-outdoors',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Camping and hiking gear',
    icon: 'mountain',
  },
  {
    name: 'Camping',
    slug: 'camping',
    parentSlug: 'outdoor-adventure',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Tents, sleeping bags and gear',
    icon: 'tent',
  },
  {
    name: 'Hiking',
    slug: 'hiking-gear',
    parentSlug: 'outdoor-adventure',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Boots, poles and bags',
    icon: 'mountain',
  },
  {
    name: 'Cycling',
    slug: 'cycling',
    parentSlug: 'sports-outdoors',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Bicycles and accessories',
    icon: 'bike',
  },
  {
    name: 'Road Bikes',
    slug: 'road-bikes',
    parentSlug: 'cycling',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Speed bikes',
    icon: 'bike',
  },
  {
    name: 'Water Sports',
    slug: 'water-sports',
    parentSlug: 'sports-outdoors',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Swimming and diving gear',
    icon: 'waves',
  },
  {
    name: 'Team Sports',
    slug: 'team-sports',
    parentSlug: 'sports-outdoors',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Football, basketball, etc.',
    icon: 'users',
  },
  {
    name: 'Football',
    slug: 'football-soccer',
    parentSlug: 'team-sports',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Balls, boots, kits',
    icon: 'life-buoy',
  },
  {
    name: 'Basketball',
    slug: 'basketball-gear',
    parentSlug: 'team-sports',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Balls, shoes, hoops',
    icon: 'life-buoy',
  },
  {
    name: 'Tennis',
    slug: 'tennis-equipment',
    parentSlug: 'sports-outdoors',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Rackets, balls',
    icon: 'circle',
  },
  {
    name: 'Racket Sports',
    slug: 'racket-sports',
    parentSlug: 'sports-outdoors',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Badminton and more',
    icon: 'circle',
  },

  // --- TOYS, BOOKS, AUTO, ETC (25) ---
  {
    name: 'Toys & Games',
    slug: 'toys-games',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Toys for all ages',
    icon: 'puzzle',
  },
  {
    name: 'Action Figures',
    slug: 'action-figures',
    parentSlug: 'toys-games',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Heroes and robots',
    icon: 'user',
  },
  {
    name: 'Board Games',
    slug: 'board-games',
    parentSlug: 'toys-games',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Family board games',
    icon: 'grid',
  },
  {
    name: 'Educational',
    slug: 'educational-toys',
    parentSlug: 'toys-games',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'STEM and learning toys',
    icon: 'graduation-cap',
  },
  {
    name: 'Books & Stationery',
    slug: 'books-stationery',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Books, pens and paper',
    icon: 'book',
  },
  {
    name: 'Fiction',
    slug: 'fiction-books',
    parentSlug: 'books-stationery',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Fantasy, Sci-Fi, Romance',
    icon: 'book-open',
  },
  {
    name: 'Art Supplies',
    slug: 'art-supplies-stationery',
    parentSlug: 'books-stationery',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Paints, brushes',
    icon: 'palette',
  },
  {
    name: 'Automotive',
    slug: 'automotive',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Car parts and accessories',
    icon: 'car',
  },
  {
    name: 'Car Accessories',
    slug: 'car-accessories',
    parentSlug: 'automotive',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Interior and exterior',
    icon: 'car',
  },
  {
    name: 'Grocery',
    slug: 'grocery',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Daily essentials',
    icon: 'shopping-cart',
  },
  {
    name: 'Snacks',
    slug: 'snacks-grocery',
    parentSlug: 'grocery',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Chips, cookies',
    icon: 'cookie',
  },
  {
    name: 'Tools',
    slug: 'home-tools',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Hardware and power tools',
    icon: 'wrench',
  },
  {
    name: 'Hand Tools',
    slug: 'hand-tools',
    parentSlug: 'home-tools',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Hammers, screwdrivers',
    icon: 'wrench',
  },
  {
    name: 'Pet Supplies',
    slug: 'pet-supplies',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Food and toys for pets',
    icon: 'heart',
  },
  {
    name: 'Dog Supplies',
    slug: 'dog-supplies',
    parentSlug: 'pet-supplies',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Food, toys and beds',
    icon: 'heart',
  },
  {
    name: 'Cat Supplies',
    slug: 'cat-supplies',
    parentSlug: 'pet-supplies',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Litter, toys and food',
    icon: 'smile',
  },
  {
    name: 'Baby & Kids',
    slug: 'baby-kids',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Diapers, toys and clothes',
    icon: 'baby',
  },
  {
    name: 'Diapers',
    slug: 'baby-diapers',
    parentSlug: 'baby-kids',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Disposable and cloth',
    icon: 'layers',
  },
  {
    name: 'Baby Food',
    slug: 'baby-food',
    parentSlug: 'baby-kids',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Formula and snacks',
    icon: 'utensils',
  },
  {
    name: 'Industrial',
    slug: 'industrial-scientific',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Equipment and safety',
    icon: 'shield',
  },
  {
    name: 'Safety Gear',
    slug: 'safety-gear',
    parentSlug: 'industrial-scientific',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Gloves, helmets',
    icon: 'shield',
  },
  {
    name: 'Music',
    slug: 'musical-instruments',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Guitars, keyboards, drums',
    icon: 'music',
  },
  {
    name: 'Guitars',
    slug: 'guitars',
    parentSlug: 'musical-instruments',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Acoustic and electric',
    icon: 'music',
  },
  {
    name: 'Movies',
    slug: 'movies-tv',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'DVDs and Blu-rays',
    icon: 'tv',
  },
  {
    name: 'Video Games',
    slug: 'video-games',
    status: PRODUCT_STATUS.PUBLISHED,
    description: 'Consoles and games',
    icon: 'gamepad',
  },
];

async function seed() {
  const uri = 'mongodb://localhost:27017/dev_db';
  console.log('Connecting to MongoDB...');
  await mongoose.connect(uri);

  const CatSchema = new mongoose.Schema(
    {
      name: String,
      slug: String,
      path: String,
      level: Number,
      status: String,
      description: String,
      icon: String,
      deletedAt: { type: Date, default: null },
      version: { type: Number, default: 1 },
    },
    { timestamps: true },
  );

  const Cat = mongoose.model('Category', CatSchema, 'categories');

  console.log('Cleaning existing categories...');
  await Cat.deleteMany({});

  console.log(`Seeding ${categories.length} categories...`);
  const createdMap = new Map<string, any>();

  for (const catData of categories) {
    const { parentSlug, ...rest } = catData as any;
    const categoryId = new mongoose.Types.ObjectId();
    let path = `,${categoryId.toString()},`;

    if (parentSlug) {
      const parent = createdMap.get(parentSlug);
      if (parent) {
        path = `${parent.path}${categoryId.toString()},`;
      }
    }

    const category = await Cat.create({
      ...rest,
      _id: categoryId,
      path,
      version: 1,
    });

    createdMap.set(rest.slug, category);
    console.log(`Created: ${category.name} (${category.path})`);
  }

  console.log('Seeding completed successfully!');
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
